### PR TITLE
feat(spanner): exporting transaction._rolled_back as transaction.rolled

### PR DESCRIPTION
**Pull request by HemangChothani**
IPR  [13]

### CODE REVIEW

**Review by IlyaFaer — APPROVED** [review]
Looks okay

**Review by mf2199 — COMMENTED** [review]
Overall looks good.
Alternatively, the changes could be confined to the Transaction class:
```
    @property
    def rolled_back(self):
        return self._rolled_back

    @rolled_back.setter
    def rolled_back(self, value):
        self._rolled_back = value
```
which may also help with backwards compatibility.

**Comment by HemangChothani** [comment]
@mf2199  Yes , true but not sure about give an access through class property as they need to expose as a class variable like ClassName.Variable.
I am confused, Should i make that change or let googler comment on the current changes like what they want.

**Comment by mf2199** [comment]
I'd explain the alternative in the comments and ask for their opinion. Again, your solution isn't wrong.

**Comment by HemangChothani** [comment]
Merged.

**Pull request closed without merging**
